name: NexusTerm Cloud Compiler

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Pre-Download PRoot into APK Assets
      run: |
        mkdir -p app/src/main/assets
        wget -q https://github.com/proot-me/proot/releases/download/v5.3.0/proot-v5.3.0-aarch64-static -O app/src/main/assets/proot
        echo "[SUCCESS] PRoot Engine embedded into assets!"

    - name: Build SIGNED Debug APK
      run: |
        chmod +x gradlew
        ./gradlew assembleDebug

    - name: Upload Installable APK
      uses: actions/upload-artifact@v4
      with:
        name: NexusTerm-Signed-Installable
        path: app/build/outputs/apk/debug/app-debug.apk
